name: Sync to Azure DevOps

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to Azure DevOps
      run: |
        git config --global user.email "sark2103@gmail.com"
        git config --global user.name "sarkar"
        echo "Pushing to Azure DevOps..."
        git remote add azure https://$(AZURE_DEVOPS_PAT)@https://baban0315@dev.azure.com/baban0315/github-sync/_git/github-sync
        git push azure --all
        echo "Push done."
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
